[package]
name = "celesta-react-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
celesta-composition = { path = "../composition" }
celesta-media = { path = "../media" }
celesta-remote = { path = "../remote" }
celesta-renderer = { path = "../renderer" }
serde = { workspace = true }
serde_json = { workspace = true }
